/* Generated by cbindgen from ffi/src/lib.rs; do not edit. */

#ifndef PERLDANTIC_H
#define PERLDANTIC_H

#include <stddef.h>
#include <stdint.h>

// A compiled serializer (opaque to C).
typedef struct PdSerializer PdSerializer;

// A compiled validator (opaque to C).
typedef struct PdValidator PdValidator;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns the library version as a static NUL-terminated string.
//
// The pointer is valid for the lifetime of the process and must not be freed.
const char *pd_version(void);

// Compile a validator from a core schema and an optional core config (wire JSON; `config` may
// be null). Returns null on failure and, when `error` is not null, stores an error envelope in
// `*error`, to be released with [`pd_string_free`]. Release the validator with
// [`pd_validator_free`].
//
// # Safety
// String arguments are null or NUL-terminated; `error` is null or writable.
PdValidator *pd_validator_new(const char *schema, const char *config, char **error);

// Release a validator; null is ignored.
//
// # Safety
// `validator` is null or was returned by [`pd_validator_new`] and not freed yet.
void pd_validator_free(PdValidator *validator);

// Validate host data (upstream `validate_python`): `input` is wire JSON, `options` a wire JSON
// object of keyword options or null. The extra option `input_type` is `"perl"` (the default:
// Perl words in error messages, arrays accepted as strict tuples) or `"python"` (exactly
// `validate_python`). Returns a result envelope.
//
// # Safety
// `validator` is null or a live handle; string arguments are null or NUL-terminated.
char *pd_validator_validate(const PdValidator *validator, const char *input, const char *options);

// Validate a JSON document (upstream `validate_json`): `json` points to `len` bytes of JSON
// text, `options` is a wire JSON object of keyword options or null. Returns a result envelope.
//
// # Safety
// `validator` is null or a live handle; `json` points to `len` readable bytes (or is null with
// `len` 0); `options` is null or NUL-terminated.
char *pd_validator_validate_json(const PdValidator *validator,
                                 const uint8_t *json,
                                 size_t len,
                                 const char *options);

// Compile a serializer from a core schema and an optional core config; see
// [`pd_validator_new`] for the conventions. Release it with [`pd_serializer_free`].
//
// # Safety
// String arguments are null or NUL-terminated; `error` is null or writable.
PdSerializer *pd_serializer_new(const char *schema, const char *config, char **error);

// Release a serializer; null is ignored.
//
// # Safety
// `serializer` is null or was returned by [`pd_serializer_new`] and not freed yet.
void pd_serializer_free(PdSerializer *serializer);

// Serialize to host data (upstream `to_python`): `value` is wire JSON, `options` a wire JSON
// object of keyword options or null. The envelope's `ok` is the wire value and `warning` the
// serializer warning, if any.
//
// # Safety
// `serializer` is null or a live handle; string arguments are null or NUL-terminated.
char *pd_serializer_to_python(const PdSerializer *serializer,
                              const char *value,
                              const char *options);

// Serialize to JSON text (upstream `to_json`); `options` may also hold `indent` and
// `ensure_ascii`. The envelope's `ok` is the JSON text as a string.
//
// # Safety
// `serializer` is null or a live handle; string arguments are null or NUL-terminated.
char *pd_serializer_to_json(const PdSerializer *serializer, const char *value, const char *options);

// Generate the JSON Schema of a core schema. `config` (wire JSON or null) applies to the whole
// schema like a `TypeAdapter`'s config; `options` holds `mode`, `by_alias`, `ref_template` and
// `union_format`. The envelope's `ok` is the JSON Schema and `warnings` a list of messages.
//
// # Safety
// String arguments are null or NUL-terminated.
char *pd_json_schema(const char *schema, const char *config, const char *options);

// The accessors of a URL (`{"$url": ...}` or `{"$multi_host_url": ...}` wire JSON), as
// pydantic's `Url` and `MultiHostUrl` give them: `scheme`, `username`, `password`, `host`,
// `unicode_host`, `port` (or `hosts` for a multi-host URL), `path`, `query`, `query_params`
// (a list of `[key, value]` pairs), `fragment` and `unicode_string`.
//
// # Safety
// `url` is null or NUL-terminated.
char *pd_url_parts(const char *url);

// Release a string returned by this library; null is ignored.
//
// # Safety
// `string` is null or was returned by a `pd_*` function and not freed yet.
void pd_string_free(char *string);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PERLDANTIC_H */
