/* Generated by cbindgen from ffi/src/lib.rs; do not edit. */

#ifndef PERLDANTIC_H
#define PERLDANTIC_H

#include <stddef.h>
#include <stdint.h>

// Where the host puts its answer to one call (opaque to C).
typedef struct PdReply PdReply;

// A compiled serializer (opaque to C).
typedef struct PdSerializer PdSerializer;

// A compiled validator (opaque to C).
typedef struct PdValidator PdValidator;

// A plain scalar of the host, described without allocating: `tag` 0 for `None`, 1 and 2 for
// `true` and `false`, 3 for the integer `int`, 4 for the float `float`, 5 for the UTF-8 string
// at `ptr` (`len` bytes, valid for the call).
typedef struct {
  int32_t tag;
  int64_t int_;
  double float_;
  const uint8_t *ptr;
  size_t len;
} PdScalar;

// The functions a host provides; `ctx` is passed back to each of them.
typedef struct {
  void *ctx;
  // 1 for an array read in place, 2 for a hash read in place, 0 for anything else.
  int32_t (*kind)(void *ctx, void *node);
  size_t (*array_len)(void *ctx, void *node);
  void *(*array_item)(void *ctx, void *node, size_t index);
  // The value under a key (UTF-8 bytes), or null.
  void *(*hash_get)(void *ctx, void *node, const uint8_t *key, size_t key_len);
  size_t (*hash_len)(void *ctx, void *node);
  // Fill up to `capacity` entries, in the order to visit them: key (UTF-8 bytes) and value.
  // Returns how many were written.
  size_t (*hash_entries)(void *ctx,
                         void *node,
                         const uint8_t **keys,
                         size_t *key_lens,
                         void **values,
                         size_t capacity);
  // Describe a plain scalar (see [`PdScalar`]); returns 0 for anything else, which is then
  // converted with `to_binary`.
  int32_t (*scalar)(void *ctx, void *node, PdScalar *out);
  // Write the node in the binary wire format; the bytes stay valid for the call. Returns 0
  // when the host cannot convert the node (it keeps the error and raises it afterwards).
  int32_t (*to_binary)(void *ctx, void *node, const uint8_t **bytes, size_t *len);
} PdHost;

// The host's callback: `(function id, call JSON, reply slot)`; it must answer through
// [`pd_host_reply`] before returning, and must not unwind. Null removes the callback.
typedef void (*PdHostCallback)(uint64_t, const char*, PdReply*);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns the library version as a static NUL-terminated string.
//
// The pointer is valid for the lifetime of the process and must not be freed.
const char *pd_version(void);

// Compile a validator from a core schema and an optional core config (wire JSON; `config` may
// be null). Returns null on failure and, when `error` is not null, stores an error envelope in
// `*error`, to be released with [`pd_string_free`]. Release the validator with
// [`pd_validator_free`].
//
// # Safety
// String arguments are null or NUL-terminated; `error` is null or writable.
PdValidator *pd_validator_new(const char *schema, const char *config, char **error);

// Release a validator; null is ignored.
//
// # Safety
// `validator` is null or was returned by [`pd_validator_new`] and not freed yet.
void pd_validator_free(PdValidator *validator);

// Validate host data (upstream `validate_python`): `input` is wire JSON, `options` a wire JSON
// object of keyword options or null. The extra option `input_type` is `"perl"` (the default:
// Perl words in error messages, arrays accepted as strict tuples) or `"python"` (exactly
// `validate_python`). Returns a result envelope.
//
// # Safety
// `validator` is null or a live handle; string arguments are null or NUL-terminated.
char *pd_validator_validate(const PdValidator *validator, const char *input, const char *options);

// Validate a JSON document (upstream `validate_json`): `json` points to `len` bytes of JSON
// text, `options` is a wire JSON object of keyword options or null. Returns a result envelope.
//
// # Safety
// `validator` is null or a live handle; `json` points to `len` readable bytes (or is null with
// `len` 0); `options` is null or NUL-terminated.
char *pd_validator_validate_json(const PdValidator *validator,
                                 const uint8_t *json,
                                 size_t len,
                                 const char *options);

// Compile a serializer from a core schema and an optional core config; see
// [`pd_validator_new`] for the conventions. Release it with [`pd_serializer_free`].
//
// # Safety
// String arguments are null or NUL-terminated; `error` is null or writable.
PdSerializer *pd_serializer_new(const char *schema, const char *config, char **error);

// Release a serializer; null is ignored.
//
// # Safety
// `serializer` is null or was returned by [`pd_serializer_new`] and not freed yet.
void pd_serializer_free(PdSerializer *serializer);

// Serialize to host data (upstream `to_python`): `value` is wire JSON, `options` a wire JSON
// object of keyword options or null. The envelope's `ok` is the wire value and `warning` the
// serializer warning, if any.
//
// # Safety
// `serializer` is null or a live handle; string arguments are null or NUL-terminated.
char *pd_serializer_to_data(const PdSerializer *serializer, const char *value, const char *options);

// Serialize to JSON text (upstream `to_json`); `options` may also hold `indent` and
// `ensure_ascii`. The envelope's `ok` is the JSON text as a string.
//
// # Safety
// `serializer` is null or a live handle; string arguments are null or NUL-terminated.
char *pd_serializer_to_json(const PdSerializer *serializer, const char *value, const char *options);

// [`pd_validator_validate`] with the input and the result in the binary wire format: `input`
// points to `input_len` bytes. The returned buffer is `*len` bytes long and must be released
// with [`pd_buffer_free`]: `B` and the result value; `W`, the warning's length (`u32`, little
// endian) and UTF-8 bytes, then the value; or `J` and a JSON error envelope.
//
// # Safety
// `validator` is null or a live handle; `input` is null or points to `input_len` bytes;
// `options` is null or NUL-terminated; `len` is null or writable.
uint8_t *pd_validator_validate_binary(const PdValidator *validator,
                                      const uint8_t *input,
                                      size_t input_len,
                                      const char *options,
                                      size_t *len);

// Whether the input is valid: [`pd_validator_validate_binary`] without the validated value,
// which the caller does not need. The buffer holds `B` and a boolean; invalid input is `false`,
// not an error. Anything else that fails (malformed input, an exception of a host function)
// is a `J` error envelope, as for validation.
//
// # Safety
// As for [`pd_validator_validate_binary`].
uint8_t *pd_validator_check_binary(const PdValidator *validator,
                                   const uint8_t *input,
                                   size_t input_len,
                                   const char *options,
                                   size_t *len);

// Validate host data read in place: `root` is a node of `host` (see [`host_input::PdHost`]).
// Returns the result as [`pd_validator_validate_binary`] does; when the host fails to convert a
// value, the result is an error envelope and the host raises its own error.
//
// # Safety
// `validator` is null or a live handle; `host` points to a table whose functions accept
// `root` and every node they return, for the whole call; `options` is null or NUL-terminated;
// `len` is null or writable.
uint8_t *pd_validator_validate_host(const PdValidator *validator,
                                    const PdHost *host,
                                    void *root,
                                    const char *options,
                                    size_t *len);

// [`pd_validator_validate_host`] answering only whether the input is valid, as
// [`pd_validator_check_binary`] does.
//
// # Safety
// As for [`pd_validator_validate_host`].
uint8_t *pd_validator_check_host(const PdValidator *validator,
                                 const PdHost *host,
                                 void *root,
                                 const char *options,
                                 size_t *len);

// [`pd_serializer_to_data`] with the value and the result in the binary wire format, returned
// as [`pd_validator_validate_binary`] returns its result.
//
// # Safety
// As for [`pd_validator_validate_binary`], with a live serializer handle.
uint8_t *pd_serializer_to_data_binary(const PdSerializer *serializer,
                                      const uint8_t *value,
                                      size_t value_len,
                                      const char *options,
                                      size_t *len);

// [`pd_serializer_to_json`] with the value in the binary wire format; the JSON text comes back
// as a string value in the buffer, as [`pd_validator_validate_binary`] returns its result.
//
// # Safety
// As for [`pd_serializer_to_data_binary`].
uint8_t *pd_serializer_to_json_binary(const PdSerializer *serializer,
                                      const uint8_t *value,
                                      size_t value_len,
                                      const char *options,
                                      size_t *len);

// Release a buffer returned by a binary export; null is ignored.
//
// # Safety
// `buffer` is null or was returned by a binary export with length `len`, and not freed yet.
void pd_buffer_free(uint8_t *buffer, size_t len);

// Generate the JSON Schema of a core schema. `config` (wire JSON or null) applies to the whole
// schema like a `TypeAdapter`'s config; `options` holds `mode`, `by_alias`, `ref_template` and
// `union_format`. The envelope's `ok` is the JSON Schema and `warnings` a list of messages.
//
// # Safety
// String arguments are null or NUL-terminated.
char *pd_json_schema(const char *schema, const char *config, const char *options);

// The accessors of a URL (`{"$url": ...}` or `{"$multi_host_url": ...}` wire JSON), as
// pydantic's `Url` and `MultiHostUrl` give them: `scheme`, `username`, `password`, `host`,
// `unicode_host`, `port` (or `hosts` for a multi-host URL), `path`, `query`, `query_params`
// (a list of `[key, value]` pairs), `fragment` and `unicode_string`.
//
// # Safety
// `url` is null or NUL-terminated.
char *pd_url_parts(const char *url);

// Release a string returned by this library; null is ignored.
//
// # Safety
// `string` is null or was returned by a `pd_*` function and not freed yet.
void pd_string_free(char *string);

// Register the host's callback (or remove it with a null pointer). Functions in schemas can
// only be called while a callback is registered.
void pd_set_host_callback(PdHostCallback callback);

// Answer a call: `result` is the reply JSON, copied before this returns.
//
// # Safety
// `reply` is the slot the callback received, during that callback; `result` is a
// NUL-terminated string.
void pd_host_reply(PdReply *reply, const char *result);

// Validate `input` with a wrap validator's `handler` (from a `validate_wrap` call), errors
// located under `outer_location` (JSON: a string, an integer or `null`; may be null).
//
// # Safety
// `handler` is the value of a `validate_wrap` call that has not returned yet; the strings
// are NUL-terminated.
char *pd_validator_handler_call(void *handler, const char *input, const char *outer_location);

// Serialize `value` with a wrap serializer's `handler` (from a `serialize_wrap` call);
// `index_key` (JSON: a list index or a dict key, or `null`; may be null) applies `include` /
// `exclude` at that position, and a filtered-out value is a `PydanticOmit` error.
//
// # Safety
// As for [`pd_validator_handler_call`], with a `serialize_wrap` call's handler.
char *pd_serializer_handler_call(void *handler, const char *value, const char *index_key);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PERLDANTIC_H */
